# Generated by Django 4.0.3 on 2022-03-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_follower_count_user_following_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follower_count',
            new_name='followercount',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='following_count',
            new_name='followingcount',
        ),
    ]
