# Generated by Django 4.0.3 on 2022-03-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followercount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followingcount',
        ),
    ]
